### ISSUE TITLE
Basepath not passed to $app constructor

### ISSUE THREAD

**Issue by heidilux** [fungku/kwiki#2]
Was running into issues where everything was referencing the `[appRoot]/public` directory.  

Solved by passing the basePath to the constructor in `bootstrap/app.php`

```
$app = new Laravel\Lumen\Application(realpath(__DIR__.'/../'));
```

Taylor's commit: https://github.com/laravel/lumen/commit/d1b9f866c30a8d93e8a118effd50b54dd39fd90e

**Comment by ryanwinchester** [comment]
thanks
