### ISSUE TITLE
kwiki is not working out of the box

### ISSUE THREAD

**Issue by whoan** [fungku/kwiki#7]
Hi Ryan,
Due to it's been more than a week since you merge some commits to fix some bugs, I just want to mention that if I install **kwiki** in the way you do in the readme.md, it's still not working out of the box. Notice it's not just **kwiki** and the problems in the namespaces, if I fix those by hand, the Subcategories links are not working because of **Pagemark** is forming wrongly the uri's.

Could you create a new release for both packages in order to let composer to fetch the last changes?

Thanks for sharing your projects, they are very useful.

**Comment by ryanwinchester** [comment]
Thanks for the reminder
